version: 1618478518032
language: cn
aomori_widgets:
  - toc
  - category
  - recent_posts
  - archive
aomori_menu:
  主&nbsp;&nbsp;&nbsp;页: /
  文&nbsp;&nbsp;&nbsp;章: /archives
  关&nbsp;&nbsp;&nbsp;于: /about
share: false
